Enhancement calculus improvements
open-algebra/Oasis pull request #119
Opened 2024-07-25 17:54 UTC by 404Naz

Fixed some existing problems. Added improvements for derivative and integral of logarithms.

2024-07-25 19:06 UTC, matthew-mccall requested changes

2024-07-26 13:46 UTC, matthew-mccall requested changes

2024-07-26 13:46 UTC, matthew-mccall commented on extras/src/MathMLSerializer.cpp
> -    //    inte->SetText("\u222B;");
Just remove the code if its not needed

2024-07-26 13:46 UTC, matthew-mccall commented on extras/src/MathMLSerializer.cpp
> +    result->SetText("&pi");
It's `&pi;`

2024-07-26 13:46 UTC, matthew-mccall commented on include/Oasis/Magnitude.hpp
> +        auto simpOpU = this->GetOperand().Generalize();
You don't have to generalize to turn call `Simplify`

2024-07-26 18:00 UTC, 404Naz commented on extras/src/MathMLSerializer.cpp
> +    result->SetText("&pi");
What is &pi?

2024-07-26 18:00 UTC, 404Naz commented on extras/src/MathMLSerializer.cpp
> -    //    inte->SetText("\u222B;");
It is removed... If it is there on the branch, I do not know how to remove it.

2024-07-30 17:47 UTC, matthew-mccall approved these changes
LGTM

2024-07-30 17:47 UTC, merged