Feature LaTex Serializer
open-algebra/Oasis pull request #136
Opened 2024-10-18 20:47 UTC by 404Naz

Wrote a serializer to translate our nodes into strings formatted for LaTex. Fixed a problem with Unary Expression's Generalize() deleting child node when copying/returning.

2024-10-22 00:11 UTC, matthew-mccall requested changes
Mostly good with some nitpicks here and there. However it would be better if we could rename everything to LaTeX which is the proper capitlization.

2024-10-22 00:11 UTC, matthew-mccall commented on io/include/Oasis/LatexSerializer.hpp
> +public:
`public` is implicit for `struct`s

2024-10-22 00:11 UTC, matthew-mccall commented on io/src/LatexSerializer.cpp
> +LatexSerializer::LatexSerializer(LatexOptions& options)
Use member initialization list

2024-10-22 00:11 UTC, matthew-mccall commented on io/src/LatexSerializer.cpp
> +LatexSerializer::LatexSerializer(){
Use delegating constructor

2024-10-22 00:11 UTC, matthew-mccall commented on io/src/LatexSerializer.cpp
> +void LatexSerializer::Serialize(const Real& real)
Make the number of decimal places an option in LaTexOptions

2024-10-22 00:11 UTC, matthew-mccall commented on io/src/LatexSerializer.cpp
> +void LatexSerializer::Serialize(const Imaginary& imaginary)
Maybe we generalize ParseOptions, because we want to give the user the option to use "j" here.

2024-10-22 00:11 UTC, matthew-mccall commented on io/src/LatexSerializer.cpp
> +    result = "\\left(\\frac{" + mostSigOpStr + "}{" + leastSigOpStr + "}\\right)";
Use fmt library. You can escape the brackets with backslashes. This goes for the next couple of lines

2024-10-22 00:11 UTC, matthew-mccall commented on io/src/LatexSerializer.cpp
> +    result = "\\left(\\frac{" + mostSigOpStr + "}{" + leastSigOpStr + "}\\right)";
Also add an option to use \div instead of fractions

2024-10-22 20:00 UTC, 404Naz commented on io/include/Oasis/LatexSerializer.hpp
> +public:
So do you want me to remove it? I am not quite sure what you want.

2024-10-22 20:50 UTC, 404Naz commented on io/src/LatexSerializer.cpp
> +LatexSerializer::LatexSerializer(LatexOptions& options)
For the options or the serializer?

2024-10-22 21:24 UTC, 404Naz commented on io/src/LatexSerializer.cpp
> +void LatexSerializer::Serialize(const Imaginary& imaginary)
I added it to LaTeX options if that is what you wanted.

2024-10-25 20:46 UTC, 404Naz commented on io/src/LatexSerializer.cpp
> +    result = "\\left(\\frac{" + mostSigOpStr + "}{" + leastSigOpStr + "}\\right)";
Escaping is {{ or }} for { or } respectively

2024-10-29 00:26 UTC, matthew-mccall approved these changes

2024-10-29 00:27 UTC, matthew-mccall requested changes

2024-10-29 00:27 UTC, matthew-mccall commented on io/include/Oasis/LatexSerializer.hpp
> +public:
Yes

2024-10-29 00:36 UTC, matthew-mccall approved these changes

2024-10-29 00:40 UTC, merged