Added some expanded cases
open-algebra/Oasis pull request #36
Opened 2023-11-07 22:37 UTC by 404Naz

Added cases for adding Expressions and exponent division.

2023-11-07 23:23 UTC, AnthonyN1 commented
We love comparing signed and unsigned types.

2023-11-10 20:01 UTC, 404Naz commented
I did not change anything in divide but the tests have broken...not sure if something I added or changed did something or they were always broken.

2023-11-15 05:45 UTC, matthew-mccall requested changes

2023-11-15 05:45 UTC, matthew-mccall commented on src/Add.cpp
> +    }
This is good. Try using more descriptive variable names such as `twoSameExprCase` instead. Also, note that you're working with the `Generalized version of `Add` so there's no need to `Specialize` it into `Add<Expression>`

2023-11-15 05:50 UTC, matthew-mccall commented on src/Add.cpp
> +    }
While the above is one example, you specialize to `Expression` children quite often. Please keep in mind that is not necessary as we are already working in the `Generalize`d version of this expression. Also there are some redundant simplifications with adding `Exponent` and `Imaginary`. Namely the cases: $i+i=2i$ and $x^y+x^y=2x^y$

2024-09-03 12:33 UTC, matthew-mccall commented
Closed due to inactivity

2024-09-03 12:33 UTC, closed without merging